### ISSUE TITLE
Use es6 Arrow function without using return keyword

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/reverse-string-js-problem-saikiran290695#1]
https://github.com/sro-boeing-wave-2/reverse-string-js-problem-saikiran290695/blob/d62a6fc79ba607bf781e43efd2f4ebe7e0d01307/reverse-using-built-in-function.js#L3-L6

**Comment by saikiran290695** [comment]
Modified arrow function to single line code.
